theme: jekyll-theme-architect

source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

nav:
  - text: HOME
    url: /marcodadamo.github.io
  - text: CATEGORIES
    url: /pages/agritradecloudagriculturalfair.html
